#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/schedule_user?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
#    username: (schedule)QUbczcjxjchQR+rVnsm/uzmeOzfHwdgf5jrnQj9nF8g=
#    password: (schedule)b2A576pm1072ITHsAijGsw8kxkNSth/2tvx10JQEmkSwPocVOLNOuxDs90q5CBAO
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    name: (schedule)ShuBdwFN1ENGFxStNDEolJqj7+uEhUqx1YrNAbreK8U=

spring:
  profiles:
    include: quartz
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/schedule_user?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: (schedule)QUbczcjxjchQR+rVnsm/uzmeOzfHwdgf5jrnQj9nF8g=
      password: (schedule)b2A576pm1072ITHsAijGsw8kxkNSth/2tvx10JQEmkSwPocVOLNOuxDs90q5CBAO
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: (schedule)ShuBdwFN1ENGFxStNDEolJqj7+uEhUqx1YrNAbreK8U=
      #      driver-class-name: com.mysql.cj.jdbc.Driver
      #      url: jdbc:mysql://localhost:3306/schedule_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useAffectedRows=true
      #      username: root
      #      password: admin
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        allow:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true