server:
  port: 8161
spring:
  application:
    name: serviceConsume1
  freemarker:
    prefer-file-system-access: false
eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://joven:123456@center-master:8761/eureka/
    #eureka client刷新本地缓存时间
    #默认30s
    registry-fetch-interval-seconds: 5
###设置feign客户端超时时间
ribbon:
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ReadTimeout: 5000
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ConnectTimeout: 5000
#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
#开启 Feign 对 Hystrix 的支持
  hystrix:
    enabled: true
  compression:
    request:   # 请求  由于开启GZIP压缩之后，Feign之间的调用数据通过二进制协议进行传输
      enabled: false # true 开启
      min-request-size: 2048 #配置压缩数据大小的下限
      mime-types: text/xml,application/xml,application/json #开启支持压缩的MIME TYPE
    response:  #响应
      enabled: false  # true 开启响应GZIP压缩