spring:
  cloud:
    inetutils:
      ignoredInterfaces: [ 'VMware.*','VirtualBox.*' ]
      use-only-site-local-interfaces: true
    config:
      discovery:
        enabled: true
        service-id: localhost
    gateway:
      #开启服务列表发现并拥有默认路由功能
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
          # 忽略大小写匹配，默认为 false。注册中心是啥就是写啥， 为true时 全转为小写的
          # 当 eureka 自动大写 serviceId 时很有用。 所以 SERIVCE,会匹配 /service/
          # demo：为true时 使用注册中心自动路由方式需要 使用小写的服务名
          # 为false 时 使用注册中心模式需要按照中心的展示方式
          lower-case-service-id: true
      routes:
        # http://localhost:8600/admin/** --> http://admin/admin/**
        - id: admin0
          uri: lb://admin
          predicates:
            - Path=/admin/**
        # http://localhost:8600/adminroute1/admin/noauth/service/syncApUserInfo -->
        # http://localhost:8080/admin/noauth/service/syncApUserInfo
        # 不建议使用这种模式
        - id: admin1
          uri: http://localhost:8080/admin/
          predicates:
            - Path=/adminroute1/**
          filters:
            - StripPrefix=1
        # http://localhost:8600/adminroute2/admin/noauth/service/syncApUserInfo -->
        # http://admin/admin/noauth/service/syncApUserInfo
        - id: admin2
          uri: lb://admin
          predicates:
            - Path=/adminroute2/**
          filters:
            - StripPrefix=1
        # http://localhost:8600/systemroute/system/sys/info -->
        # http://system/system/sys/info
        - id: system0
          uri: lb://system
          predicates:
            - Path=/systemroute/**
          filters:
            - StripPrefix=1
        # http://localhost:8600/system/sys/info -->
        # http://system/system/sys/info
        - id: system1
          uri: lb://system
          predicates:
            - Path=/system/**
