management:
  endpoints:
    enabled-by-default: false #不暴露所有端点信息
    web:
      exposure:
        include: mappings  #以web方式暴露
  endpoint:
    mappings:
      enabled: true
  health:
    redis:
      enabled: false
#eureka
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://center-second:8762/eureka/
    registry-fetch-interval-seconds: 5