server:
  port: 8961
spring:
  application:
    name: serviceZuul
  freemarker:
    prefer-file-system-access: false
eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://joven:123456@center-master:8761/eureka/
    #eureka client刷新本地缓存时间
    #默认30s
    registry-fetch-interval-seconds: 5
#Zuul de 配置
zuul:
  routes:
    cxytiandi:
      #两个星号表示可以转发任意层级的 URL ，比如“/api/house/l ” 。 如果只配置一个星号，那么就只能转发一级， 比如“/api/house ”
      path: /cxytiandi/**   #通过 zuul.routes 来配置路由的地址时，就会跳转到 http://cxytiandi.com 上
      url: http://cxytiandi.com/
  # 开启重试
  retryable: true
ribbon:
  eureka:
    # 开启 Eureka
    enabled: true
