server:
  port: 8761
spring:
  application:
    name: eureka-center
  freemarker:
    prefer-file-system-access: false
    # Eureka 认证
  security:
    basic:
      enabled: true
    user:
      name: joven
      password: 123456
eureka:
  instance:
    #hostname: center-master
    hostname: ${spring.cloud.client.ip-address}
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true # 由于已经是注册中心 false 表示就不再向中心注册自己
    fetch-registry: true # 是不是要去检索其他的服务 false注册中心就是维护服务实例的不再去检索
    serviceUrl:
      #设置服务注册中心地址，指向另一个注册中心
      defaultZone: http://center-second:8762/eureka/
    #eureka client刷新本地缓存时间
    #默认30s
    registry-fetch-interval-seconds: 5
  server:
    #eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
    #默认30s
    response-cache-update-interval-ms: 5000
    #启用主动失效，并且每次主动失效检测间隔为3s
    eviction-interval-timer-in-ms: 5000
    peer-node-read-timeout-ms: 5000