mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
  # config-location: classpath:/mybatis/config/mybatis-config.xml  # 与 configuration 配置冲突 不能同时使用
  type-aliases-package: org.joven.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'